dist: trusty
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npx cypress run
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &

